FROM ubuntu:20.04

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/root

# base
RUN echo "Asia/Shanghai" > /etc/timezone
RUN sed -i -E -e "s,http://.*com/,http://mirrors.aliyun.com/," -e "s,^\# deb-src,deb-src," /etc/apt/sources.list &&\
	apt-get -y update &&\
	unminimize <<< $'y\n\n' &&\
	apt-get -y install tzdata locales git vim man iproute2 iputils-ping psmisc ssh curl file tmux zsh

# development
RUN apt-get -y install build-essential bison flex libelf-dev libssl-dev libncurses-dev bc qemu-system-x86 kmod cpio clang strace ltrace

# docker
RUN apt-get -y install ca-certificates curl gnupg lsb-release &&\
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg &&\
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
	https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&\
	apt-get -y update &&\
	apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin

ENV ALL_PROXY=socks5://192.168.0.107:7890
#ENV MIRRO_GITHUB=https://hub.fastgit.xyz

RUN locale-gen en_US.UTF-8 &&\
	update-alternatives --install /usr/bin/python python /usr/bin/python3 3 &&\
	[ -n "${MIRRO_GITHUB}" ] && git config --global url.${MIRRO_GITHUB}.insteadOf https://github.com || true


# utils ( ohmyzh starship broot.. )
RUN git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git $HOME/.oh-my-zsh &&\
	cp $HOME/.oh-my-zsh/templates/zshrc.zsh-template $HOME/.zshrc &&\
	sed -i -e 's/^plugins=(git)/plugins=(git\n)/' $HOME/.zshrc &&\
	sed -i -e '/^plugins=(git/a \docker z zsh-navigation-tools command-not-found aliases'\
		-e 's/^# export LANG=en_US.UTF-8/export LANG=en_US.UTF-8/' $HOME/.zshrc &&\
	git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git \
		${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting &&\
	sed -i -e '/^plugins=(git/a \zsh-syntax-highlighting' $HOME/.zshrc &&\
	git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions.git \
		${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions &&\
	sed -i -e '/^plugins=(git/a \zsh-autosuggestions' $HOME/.zshrc

RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes &&\
		echo 'eval "$(starship init zsh)"' >> $HOME/.zshrc &&\
	curl -sS -o /usr/local/bin/broot https://dystroy.org/broot/download/x86_64-linux/broot &&\
		chmod a+x /usr/local/bin/broot && broot --install &&\
	git clone --depth 1 https://github.com/so-fancy/diff-so-fancy.git /usr/local/lib/diff-so-fancy &&\
		ln -s ../lib/diff-so-fancy/diff-so-fancy /usr/local/bin/diff-so-fancy

RUN apt-get -y install fzf bat keychain &&\
	echo 'eval "$(keychain --eval id_rsa)"' >> $HOME/.zprofile

ADD config /usr/local/config/
ADD entry.sh /usr/local/bin/


RUN mkdir /run/sshd && ssh-keygen -f $HOME/.ssh/id_rsa -N "" &&\
	ln -s /usr/local/config/starship.toml $HOME/.config/starship.toml


CMD [ "/bin/bash", "/usr/local/bin/entry.sh"]
