set nocompatible
set backspace=indent,eol,start


set number
set hlsearch

set autoindent
set smartindent
set tabstop=4

set ruler
set incsearch
"set mouse=a

if &diff
	colorscheme elflord
else
	colorscheme pablo
endif

syntax on
